# -*- coding: utf-8 -*-

from main import view_list
from edit import edit_by_id
from edit import ajax_add_kiosk
from edit import settings
from edit import add
from tariff import tariff_values
from tariff import kiosk_tariff_plans
from tariff import revert_tariff_values
from permission import permissions
from permission import add_permission
from permission import remove_permission
from slot import kiosk_slots
from slot import ajax_order_by
from slot import ajax_review_inventory
from slot import ajax_review_all
from slot import ajax_review_kill
from slot import ajax_disk_to_eject
from screen import screens
from screen import make_screen
from trailer import trailers_schedule
from trailer import ajax_disable
from bash import kiosk_bash
from bash import ajax_kiosk_bash
from calibration import kiosk_calibration
from calibration import ajax_kiosk_calibration
from multi import multi_settings
from multi import global_review_inventory
